### ISSUE TITLE
Unable to pass game preinit event

### ISSUE THREAD

**Issue by TooVeryIcey** [pie-flavor/Tattle#1]
[19:43:04 ERROR] [Sponge]: Could not pass GamePreInitializationEvent$Impl to Plugin{id=tattle, name=Tattle, version=1.1.1, description=A reports plugin., authors=[pie_flavor], source=mods/Tattle-1.2.0.jar}
java.nio.file.NoSuchFileException: /root/Server/config/tattle/storage.dat
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_162]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_162]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_162]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_162]
        at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_162]
        at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_162]
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_162]
        at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_162]
        at flavor.pie.tattle.Tattle.load(Tattle.java:321) ~[Tattle.class:?]
        at flavor.pie.tattle.Tattle.preInit(Tattle.java:97) ~[Tattle.class:?]
        at org.spongepowered.common.event.listener.GamePreInitializationEventListener_Tattle_preInit49.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:408) [SpongeEventManager.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:435) [SpongeEventManager.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:213) [SpongeImpl.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:221) [SpongeImpl.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.server.SpongeVanilla.preInitialize(SpongeVanilla.java:121) [SpongeVanilla.class:1.12.2-7.1.0-BETA-33]
        at net.minecraft.server.dedicated.DedicatedServer.handler$onServerLoad$bac000(SourceFile:1234) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:117) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:434) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]

**Comment by TooVeryIcey** [comment]
Closed?
